### ISSUE TITLE
Wrong buttons order

### ISSUE THREAD

**Issue by ghost** [thiagokimo/KonamiCode#2]
Now to display toast we should click B, A and Start.

**Comment by thiagokimo** [comment]
It already has this behavior, right? Whenever a button is pressed I check if it belongs to the correct sequence (B, A and Start).

https://github.com/thiagokimo/KonamiCode/blob/master/library/src/main/java/io/kimo/konamicode/KonamiCodeLayout.java#L204

**Comment by ghost** [comment]
But hint message say: "Press the buttons in the order: A, B and START".

**Comment by thiagokimo** [comment]
Oh, I got it. You're saying that the message is wrong in the example app! 

I'm gonna fix this :)

**Comment by thiagokimo** [comment]
Done! I've uploaded a new version of the example app. The message is now correct.

Thank you o/
