### ISSUE TITLE
Only A and START visible.

### ISSUE THREAD

**Issue by eliasbrange** [thiagokimo/KonamiCode#4]
Button B is not visible inside the popup, only A and START is shown. 

I have a RelativeLayout with one view for the game and one for banner ads. The konami code is added after the views are initialized.

**Comment by thiagokimo** [comment]
Is this more or less what you have?

```
<RelativeLayout>
--<GameView>
--<BannerView>   
```

Can you also give me a screenshot of the screen? (if possible)
I guess its a problem of the alert dialog I use to show the buttons with the default theme you have...

**Comment by thiagokimo** [comment]
Fixed in release `1.1.6`
